import type { editor } from "monaco-editor";

export const DEVWORKSPACE_DARK_THEME = "devworkspace-dark";
export const DEVWORKSPACE_LIGHT_THEME = "devworkspace-light";

type MonacoThemeData = editor.IStandaloneThemeData;

const DARK_RULES: MonacoThemeData["rules"] = [
  { token: "comment", foreground: "6b6b76", fontStyle: "italic" },
  { token: "keyword", foreground: "c586c0" },
  { token: "keyword.control", foreground: "c586c0" },
  { token: "string", foreground: "a5c882" },
  { token: "string.escape", foreground: "e5c07b" },
  { token: "number", foreground: "e5c07b" },
  { token: "regexp", foreground: "d19a66" },
  { token: "type", foreground: "e5c07b" },
  { token: "type.identifier", foreground: "e5c07b" },
  { token: "identifier", foreground: "d4d4d8" },
  { token: "function", foreground: "61afef" },
  { token: "variable", foreground: "d4d4d8" },
  { token: "constant", foreground: "d19a66" },
  { token: "operator", foreground: "89ddff" },
  { token: "delimiter", foreground: "8a8a96" },
  { token: "delimiter.bracket", foreground: "8a8a96" },
  { token: "delimiter.parenthesis", foreground: "8a8a96" },
  { token: "tag", foreground: "e06c75" },
  { token: "attribute.name", foreground: "d19a66" },
  { token: "attribute.value", foreground: "a5c882" },
  { token: "metatag", foreground: "e06c75" },
  { token: "invalid", foreground: "ff5555" },
];

const DARK_COLORS: Record<string, string> = {
  "editor.background": "#0b0b0f",
  "editor.foreground": "#d4d4d8",
  "editorCursor.foreground": "#e8e8ec",
  "editor.lineHighlightBackground": "#16161c",
  "editor.selectionBackground": "#3a3a45",
  "editor.inactiveSelectionBackground": "#2a2a33",
  "editorLineNumber.foreground": "#4a4a55",
  "editorLineNumber.activeForeground": "#9a9aa5",
  "editorIndentGuide.background": "#1c1c24",
  "editorIndentGuide.activeBackground": "#38383f",
  "editorWhitespace.foreground": "#2a2a33",
  "editorWidget.background": "#131318",
  "editorWidget.border": "#2c2c34",
  "editorSuggestWidget.background": "#131318",
  "editorSuggestWidget.border": "#2c2c34",
  "editorSuggestWidget.selectedBackground": "#24242c",
  "editorSuggestWidget.highlightForeground": "#61afef",
  "editorHoverWidget.background": "#131318",
  "editorHoverWidget.border": "#2c2c34",
  "editorBracketMatch.border": "#61afef",
  "editorBracketMatch.background": "#2c2c34",
  "editorLink.activeForeground": "#61afef",
  "scrollbarSlider.background": "#3a3a4580",
  "scrollbarSlider.hoverBackground": "#3a3a45b0",
  "scrollbarSlider.activeBackground": "#4a4a55",
  "editorGutter.background": "#0b0b0f",
  "editorOverviewRuler.border": "#1c1c24",
  "editor.lineHighlightBorder": "#00000000",
  "focusBorder": "#4a4a55",
  "editor.wordHighlightBackground": "#3a3a4526",
  "editor.wordHighlightStrongBackground": "#3a3a4526",
};

const LIGHT_RULES: MonacoThemeData["rules"] = [
  { token: "comment", foreground: "8a8472", fontStyle: "italic" },
  { token: "keyword", foreground: "a626a4" },
  { token: "keyword.control", foreground: "a626a4" },
  { token: "string", foreground: "44803e" },
  { token: "string.escape", foreground: "b5651d" },
  { token: "number", foreground: "b5651d" },
  { token: "regexp", foreground: "9a6a1f" },
  { token: "type", foreground: "986801" },
  { token: "type.identifier", foreground: "986801" },
  { token: "identifier", foreground: "3a352e" },
  { token: "function", foreground: "0f6f99" },
  { token: "variable", foreground: "3a352e" },
  { token: "constant", foreground: "b5651d" },
  { token: "operator", foreground: "9a3e2e" },
  { token: "delimiter", foreground: "6f6a5e" },
  { token: "delimiter.bracket", foreground: "6f6a5e" },
  { token: "delimiter.parenthesis", foreground: "6f6a5e" },
  { token: "tag", foreground: "c0392b" },
  { token: "attribute.name", foreground: "b5651d" },
  { token: "attribute.value", foreground: "44803e" },
  { token: "metatag", foreground: "c0392b" },
  { token: "invalid", foreground: "c0392b" },
];

const LIGHT_COLORS: Record<string, string> = {
  "editor.background": "#f3efe4",
  "editor.foreground": "#3a352e",
  "editorCursor.foreground": "#3a352e",
  "editor.lineHighlightBackground": "#e9e3d4",
  "editor.selectionBackground": "#d5cdb8",
  "editor.inactiveSelectionBackground": "#e2dccb",
  "editorLineNumber.foreground": "#b0a88f",
  "editorLineNumber.activeForeground": "#7a7266",
  "editorIndentGuide.background": "#e2dccb",
  "editorIndentGuide.activeBackground": "#c4bba5",
  "editorWhitespace.foreground": "#d5cdb8",
  "editorWidget.background": "#faf8f1",
  "editorWidget.border": "#d5cdb8",
  "editorSuggestWidget.background": "#faf8f1",
  "editorSuggestWidget.border": "#d5cdb8",
  "editorSuggestWidget.selectedBackground": "#e9e3d4",
  "editorSuggestWidget.highlightForeground": "#0f6f99",
  "editorHoverWidget.background": "#faf8f1",
  "editorHoverWidget.border": "#d5cdb8",
  "editorBracketMatch.border": "#0f6f99",
  "editorBracketMatch.background": "#e2dccb",
  "editorLink.activeForeground": "#0f6f99",
  "scrollbarSlider.background": "#b0a88f80",
  "scrollbarSlider.hoverBackground": "#b0a88fb0",
  "scrollbarSlider.activeBackground": "#8a8472",
  "editorGutter.background": "#f3efe4",
  "editorOverviewRuler.border": "#e2dccb",
  "editor.lineHighlightBorder": "#00000000",
  "focusBorder": "#b0a88f",
  "editor.wordHighlightBackground": "#d5cdb826",
  "editor.wordHighlightStrongBackground": "#d5cdb826",
};

export function defineMonacoThemes(monaco: typeof import("monaco-editor")): void {
  monaco.editor.defineTheme(DEVWORKSPACE_DARK_THEME, {
    base: "vs-dark",
    inherit: true,
    rules: DARK_RULES,
    colors: DARK_COLORS,
  });

  monaco.editor.defineTheme(DEVWORKSPACE_LIGHT_THEME, {
    base: "vs",
    inherit: true,
    rules: LIGHT_RULES,
    colors: LIGHT_COLORS,
  });
}
